trialapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
from django.views.generic.base import RedirectView
urlpatterns = [
    path('',views.home,name='home'),

    path('enroll/<title>/',views.EnrollView.as_view(),name='enroll'),
    path('contact/<title>/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    #path('signup_patient/',views.signupPatient,name='signup_patient'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('login/',views.Login.as_view(), name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('dashboard/editProfile/',views.EditProfile, name='editProfile'),
    path('listOperator/signupOperator/',views.signupOperator, name='signupOperator'),
    path('dashboard/listOperator/deleteOperator/<id>/',views.deleteOperator, name='deleteOperator'),
    path('listOperator/',views.listOperator, name='listOperator'),
    path('dashboard/createTrial/',views.createTrial, name='createTrial'),
    path('dashboard/listTrial/',views.listTrial, name='listTrial'),
    path('dashboard/listEnrollment/',views.listEnrollment, name='listEnrollment'),
    path('list_trial/deleteTrial/<title>/',views.deleteTrial, name='deleteTrial'),


    # urls for testing purpose
    path('trial_detail/<str:title>/',views.DetailTrial.as_view(),name='trial_detail'),
    path('signup_patient/', views.SignupPatient.as_view(), name='signup_patient'),
    path('update_operator/<pk>/', views.UpdateOperator.as_view(), name='update_operator'),
    path('list_trial/', views.ListTrials.as_view(), name='list_trial'),
    # path('author/',views.Author.as_view(), name='author'),
    # path('go-to-django/', RedirectView.as_view(url='https://djangoproject.com'), name='go-to-django'),

    path('dashboard/createTrial/load-cities/', views.load_cities, name='load_cities'),

    # path('nested_forms/',views.nested_forms,name='nested_forms'),
    path('nested_forms/',views.StudentView.as_view(), name='save_form_data'),
    path('nested_forms/save_form_data/', views.SaveFormData.as_view(), name='save_form_data'),
    path('nested_forms/save_data/',views.save_data, name='save_data'),
    path('file_upload/', views.upload_view, name='basic_upload'),
    path('file_upload/load_files/', views.load_files, name='load_files'),
    path('autocomplete/ajax_calls/search/', views.autocompleteModel, name='autocompletemodel'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('checkbox_heirarchy/', views.checkboxheirarchy, name='checkbox'),

]

trialsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    url(r'^',include('trialapp.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/',include('django.contrib.auth.urls')),
    # path('accounts/profile/',include('trialapp.urls')),
]

trialapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

from django.contrib.auth.models import Permission, User

class Trial(models.Model):
    title = models.CharField(max_length=100,primary_key=True)
    description = models.TextField()
    country = models.ForeignKey('Country', on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey('City', on_delete=models.SET_NULL, null=True)
    creator = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.title


class Country(models.Model):
    name = models.CharField(max_length=30)
    verbose_name = 'Countries'
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    verbose_name = 'Cities'
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Investigator(User):
    is_superuser = True


    def __str__(self):
        return self.username

class Operator(User):
    creator = models.ForeignKey(Investigator,on_delete=models.CASCADE)
    is_operator = True
    can_create_trial = models.BooleanField(default= False)

    def __str__(self):
        return self.username

class Patient(User):
    trials_enrolled = models.ManyToManyField('Trial',)
   
    def __str__(self):
        return 'Patient'

class Message(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

class Conversation(models.Model):
    sender = models.OneToOneField(User, on_delete=models.CASCADE, related_name='Sender')
    receiver = models.OneToOneField(User, on_delete=models.CASCADE, related_name='Receiver')
    message = models.ForeignKey('Message',on_delete=models.CASCADE)

    def __str__(self):
        return self.sender+" to "+self.receiver+":" + self.message


class Enrollment(models.Model):
    patient_name = models.CharField(max_length=15)
    trial = models.OneToOneField('Trial',on_delete=models.CASCADE)
    email = models.EmailField()

trialapp/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.http import HttpResponseRedirect,HttpResponse
from .forms import InvestigatorSignupForm
from .models import Investigator, Trial
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm
from .models import Operator, Enrollment
from .forms import OperatorSignupForm, ContactForm
from .forms import ListOperatorForm 
from .forms import CreateTrialForm, PatientSignupForm
from django.views import View
from django.urls import reverse, reverse_lazy

def home(request):
        
    trials = Trial.objects.all()
    return render(request,'trialapp/dashboardnew.html',{'trials':trials})
    



def signup(request):

    if request.method == 'POST':
        form = InvestigatorSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            return HttpResponseRedirect('/trialapp')
        else:
            print('not valid')
    else:
        form = InvestigatorSignupForm(request.POST)
                   
    return render(request,'trialapp/userSignup.html',{'form':form})




@login_required
def dashboard(request):
    
    #if request.method == 'POST':
        #return HttpResponseRedirect('createOperator')
    #else:
    return render(request,'trialapp/dashboard.html')




#@permission_required('trialApp.add_operator',raise_exception=True)
@login_required
def signupOperator(request):
    if request.method == 'POST':
        form = OperatorSignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            return HttpResponse('operator created')
        else:
            print('not valid')
    else:
        form = OperatorSignupForm(request.POST)

    return render(request,'trialapp/userSignup.html',{'form':form, 'successful_submit': True})



class EnrollView(View):
    form_class = PatientSignupForm
    template_name='trialapp/userSignup.html'

    def get_queryset(self):
        return self.kargs['title']

    def get(self, request,*args, **kargs):
        print(self.args['title'])
        form = self.form_class()
        print('get request')
        print(self.get_queryset())
        return render(request, self.template_name, {'form': form})



    def post(self, request, *args, **kargs):
        form = self.form_class(request.POST)

        if form.is_valid():

            return HttpResponse('Successfully signed up')
        return render(request, self.template_name, {'form': form})


@login_required
def createTrial(request):
    if request.method == 'POST':
        form = CreateTrialForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Trial Created successfully')

    else:
        form = CreateTrialForm(initial={'creator': request.user})

    return render(request,'trialapp/createTrial.html',{'form':form})



@login_required
def listTrial(request):
    trials = Trial.objects.filter(creator=request.user)
    operators = Operator.objects.filter(creator=request.user)
    # print(trials)
    for o in operators:
        trials = trials | Trial.objects.filter(creator=o)

    return render(request,'trialapp/listTrial.html',{'trials':trials})


@login_required
def listOperator(request):
    # # print(request.user.has_perm('trialapp.view_operator'))
    # if request.method == 'POST':
    #     # print(id)
    #     form = ListOperatorForm()
    #
    #
    # #else:
    #     #form = DeleteOperatorForm(request.POST)

    operators = Operator.objects.filter(creator=request.user)
    
    return render(request,'trialapp/operators.html',{'operators':operators,})



@login_required
def EditProfile(request):
    if request.method == 'POST':
        #op = Operator.objects.get(id=id)
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            
            #print(user.username)
            #inv = Investigator.objects.get(username=request.user)
            #inv.op = user
            #print(inv.op.password)
            return HttpResponse('operator updated')
        else:
            print(request.user)
            pass
    else:
        #op = Operator.objects.get(id=id)
        form = UserChangeForm(instance=request.user)
        print(request.user)
    return render(request,'trialapp/editprofile.html',{'form':form})



@login_required
def deleteOperator(request,id):
    op = Operator.objects.get(id=id)
    op.delete()
    return HttpResponse('Operator Deleted')

@login_required
def deleteTrial(request,title):
    tr = Trial.objects.get(title=title)
    tr.delete()
    return HttpResponse('Trial Deleted')



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))



#def enroll(request,title):

#    if request.method == 'POST':
#        form = EnrollmentForm(request.POST)
#        if form.is_valid():
#            form.save()
#            return HttpResponse('Successfully Enrolled')
    
#    form = EnrollmentForm(initial={'trial':title})
#    return render(request,'trialapp/enrollment.html',{'form':form})

def listEnrollment(request):
    enrolled = Enrollment.objects.all()
    return render(request,'trialapp/listEnrollment.html',{'enrolled':enrolled})


def contact(request, title):
    trial = Trial.objects.get(title=title)
    creator_username = trial.creator
    try:
            creator = Investigator.objects.get(username=creator_username)
            form = ContactForm(initial={'consultant':creator.username,'email':creator.email,})
            return render(request,'trialapp/contact.html',{'form':form})
    except: 
            creator = Operator.objects.get(username=creator_username)
            form = ContactForm(initial={'consultant':creator.username,'email':creator.email,})

            return render(request,'trialapp/contact.html',{'form':form})





# views for testing purpose     GENERIC EDITING VIEW

from django.views.generic.edit import CreateView,UpdateView, FormView
from .models import Patient
from .forms import LoginForm


from django.contrib.auth import authenticate, login, logout

from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView



''' generic display views'''



class ListTrials(ListView):
    template_name = 'trialapp/trials.html'
    success_url = '/trialapp'

    def get_queryset(self):
        trials = Trial.objects.filter(creator=self.request.user)
        operators = Operator.objects.filter(creator=self.request.user)
        # print(trials)
        for o in operators:
            trials = trials | Trial.objects.filter(creator=o)

        # return render(request, 'trialapp/listTrial.html', {'trials': trials})
        return trials

class DetailTrial(DetailView):
    template_url = 'trialapp/trial_detail.html'
    model = 'Trial'
    queryset = Trial.objects.all()
    def get_object(self):
        print(self.args)
        print(self.kwargs)
        print(self.request)
        title_ = Trial.objects.get(title=self.kwargs['title'])
        return title_



'''generic editing view'''

class SignupPatient(CreateView):
    form_class = PatientSignupForm
    template_name = 'trialapp/userSignup.html'
    success_url = '/trialapp'


class UpdateOperator(UpdateView):
    model = Operator
    # form_class = OperatorSignupForm
    # template_name = 'trialapp/operator_form.html'
    fields = ['username','first_name','last_name','first_name','email','creator']
    # success_url = '/trialapp'
    #
    # def get(self,*args,**kwargs):
    #     op = self.get_object()
    #     form = OperatorSignupForm(initial={'username':op.username})
    #     return render(self.request, self.template_name,{'form':form})
    #
    #
    #
    #

    def get_initial(self):
        initial = super(UpdateOperator, self).get_initial()
        print('initial data', initial)

        # retrieve current object
        object = self.get_object()

        initial['username'] = object.username
        initial['creator'] = object.creator

        return initial

    def get_object(self, queryset=None):
        obj = Operator.objects.get(id=self.kwargs['pk'])
        print(obj)
        return obj



class Login(FormView):
    form_class = LoginForm
    template_name = 'trialapp/userSignin.html'
    success_url = reverse_lazy(home)        #callable view object or URL pattern name

    def form_valid(self,form):
        print('form_valid method')
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            print('logged in')
            login(self.request, user)
        else:
            return HttpResponseRedirect('')

        return super().form_valid(form)

'''generic base view'''
# class Login(View):
#     # form_class = LoginForm
#     success_url = '/trialapp'
#     template_name = 'trialapp/userSignin.html'   #login.html
#     def post(self, request):
#         logout(request)
#         print('post method')
#         form = LoginForm(request.POST)
#         # username = password = ''
#         # form = self.form_class(request.POST)
#         username = form.cleaned_data['username']
#         password = form.cleaned_data['password']
#
#         user = authenticate(username=username, password=password)
#         if user is not None and user.is_active:
#             login(request, user)
#             return HttpResponseRedirect(self.success_url)
#         return render(request, self.template_name,{'form':form})
#
#     def get(self, request):
#         form = LoginForm()
#         print(' get method')
#         return render(request, self.template_name,{'form':form})





# class Author(RedirectView):
#     url_pattern = 'dashboard'
#
#     def get_redirect_url(self,*args,**kwargs):

trialapp/templates/trialapp/checkbox_heirarchy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkbox Heirarchy</title>
</head>
<body>
    {% csrf_token%}
    {{form.as_p}}
</body>
</html>

trialapp/templates/trialapp/contact.html
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
        <!--<title> Contact</title>-->
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
        <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
<!--</head>-->

<!--<body>-->
        <!--<div class="container bg-light">-->
{% extends 'base.html'%}
{% block title %} Contact {% endblock title %}
{% block content %}
                <form action="" method="POST">
                        <fieldset>
                                <legend> <h1 class='txt-info'>Contact:</h1> </legend>
                                {% csrf_token %}
                                {{form.as_p}}
                                <input type="submit" value="Email" class="btn btn-primary float-right" formaction=" "> 
                                <input type="submit" value="Message" class="btn btn-primary float-right" formaction=" ">
                        </fieldset>
                </form>
{% endblock content%}

trialapp/templates/trialapp/createTrial.html
{% extends 'trialapp/base.html' %}
{% block header %}
        <a class="navbar-brand" href="#pablo">Trials</a>
        <!--<form method="post">-->
          <!--{% csrf_token%}-->
          <!--<input type="submit" value="Create Trial" class="btn btn-primary " formaction="{% url 'createTrial' %}">-->
        <!--</form>-->
{% endblock header%}

{%block navbar %}

{% endblock navbar%}
      <!-- End Navbar -->
      {% block content %}
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Create Trial</h4>
                  <!--<p class="card-category">Complete your profile</p>-->
                </div>
                <div class="card-body">
                  <form method="post" id="personForm" data-cities-url="{% url 'load_cities' %}" novalidate>
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Title</label>
                          <!--<input type="text" class="form-control" >-->
                          {{ form.title }}
                        </div>
                      </div>
                      <div class="col-md-8">
                        <div class="form-group">
                          <label class="bmd-label-floating">Description</label>
                          <!--<input type="text" class="form-control">-->
                          {{ form.description }}
                        </div>
                      </div>

                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">Country</label>
                          <!--<input type="text" class="form-control">-->
                          {{ form.country }}

                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label class="bmd-label-floating">City</label>
                          <!--<input type="text" class="form-control">-->
                          {{ form.city }}
                        </div>
                      </div>
                      <!--<div class="col-md-4">-->
                        <!--<div class="form-group">-->
                          <!--<label class="bmd-label-floating">Email Address</label>-->
                          <!--&lt;!&ndash;<input type="text" class="form-control">&ndash;&gt;-->
                          <!--{{ form.email }}-->
                        <!--</div>-->
                      <!--</div>-->
                    </div>
                     <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Creator</label>
                          <!--<input type="text" class="form-control">-->
                          {{ form.creator }}
                        </div>
                      </div>
                     </div>
                    <button type="submit" class="btn btn-primary pull-right">Create Trial</button>

                    <div class="clearfix"></div>
                  </form>


                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card card-profile">
                <div class="card-avatar">
                  <a href="#pablo">
                    {% load static %}
                    <img class="img" src="{% static 'trialapp/assets/img/faces/danish.jpg' %}" />
                  </a>
                </div>
                <div class="card-body">
                  <!--<h6 class="card-category text-gray">CEO / Co-Founder</h6>-->
                  <h4 class="card-title">Danish Wani</h4>
                  <p class="card-description">
                    Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                  </p>
                  <a href="https://github.com/danish-wani" class="btn btn-primary btn-round">Follow</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/trialapp/dashboard/createTrial/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });





  </script>
{% endblock content%}

trialapp/templates/trialapp/dashboardnew.html
{% extends 'trialapp/base.html' %}


{% block title %} Home {% endblock title%}

{% block sidebar %}
          {% if request.user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'listOperator' %}">
              <i class="material-icons">content_paste</i>
              <p>Operator List</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="">
              <i class="material-icons">content_paste</i>
              <p>Patient List</p>
            </a>
          </li>

          <li class="nav-item ">
            <a class="nav-link" href="{% url 'list_trial' %}">
              <i class="material-icons">library_books</i>
              <p>Trials</p>
            </a>
          </li>
        {% endif %}
{% endblock sidebar%}

              {% block navbar %}
              {% if request.user.is_authenticated %}

                <li class="nav-item">
                Username: {{request.user}}
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                  <input type="submit" value="Log Out" class="btn btn-danger " data-toggle = "tooltip" title="Logout"> </a>
              </li>

              </li>
              {% else%}
                 <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}" data-toggle = "tooltip" title="Login">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">
                  <input type="submit" value="Signup As Investigator" class="btn btn-success " data-toggle = "tooltip" title="Signup"> </a>
              </li>
              {% endif %}
              {% endblock navbar%}

 {% block content %}
          <div class=" col-md-12">  <!-- col-lg-6 -->
              <div class="card">
                <div class="card-header card-header-warning">
                  <h4 class="card-title">Trials</h4>
                  <!--<p class="card-category">New employees on 15th September, 2016</p>-->
                </div>
                <div class="card-body table-responsive">
                  <table class="table table-striped">
                    <thead class="text-warning">
                      <th>Title</th>
                      <!--<th>Name</th>-->
                      <!--<th>Salary</th>-->
                      <!--<th>Country</th>-->
                      <th> </th>
                      <th> </th>
                    </thead>
                    <tbody>
                      {% for t in trials %}
                      <form method="post">
                        {% csrf_token %}
                      <tr>
                        <td><a href="{% url 'trial_detail' title=t.title %}">{{t.title}}</a></td>
                        <td><input type="submit" value="Enroll" class="btn btn-primary" formaction="{% url 'enroll' title=t.title%}"></a></td>
					    <td><input type="submit" value="Contact" class="btn btn-success " formaction="{% url 'contact' title=t.title%}"></a></td>
                      </tr>
                      </form>
                      {% endfor %}

                    </tbody>
                  </table>
                </div>
              </div>
            </div>

  {% endblock content %}

trialapp/templates/trialapp/enrollment.html
<!DOCTYPE html>
<html>
<head>
        <title> Enrollment Form</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
        <div class="container bg-light">
                <form action="" method="POST">
                        <fieldset>
                                <legend> <h1 class='txt-info'>Enrollment:</h1> </legend>
                                {% csrf_token %}
                                {{form.as_p}}
                                <input type="submit" value="Enroll" class="btn btn-primary float-right">
                        </fieldset>
                </form>
        </div>
</body>
</html>

trialapp/templates/trialapp/listOperator.html
<!DOCTYPE html>
<html>
<head>
        <title> Delete Operator  </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
        <h1> Operators: </h1>
        <div class="container bg-light">
		{% csrf_token %}
		<table class="table table-striped mx-auto">
    			<thead>
      				<tr>
					<th> ID </th>
					<th>Name</th>
					<th> Creator</th>
					<th></th>
					<th></th>
				</tr>
    			</thead>
    			<tbody>
				{% for o in operators %}
				<form method='POST'>
					{% csrf_token %}
					<tr>
					<td >{{o.id}}</td>
					<td>{{o.username}}</td>
					<td>{{o.creator}}</td>
					<td><input type="submit" value="Delete Operator" class="btn btn-danger " formaction="{% url 'deleteOperator' id=o.id %}"></a></td>
					<td><input type="submit" value="Update Operator" class="btn btn-success " formaction="{%url 'update_operator' pk=o.id %}"></a></td>
					</tr>
				</form>
				{% endfor %}
    			</tbody>
  		</table>
	</div>
</body>
</html>

trialapp/templates/trialapp/listTrial.html
<!DOCTYPE html>
<html>
<head>
        <title> Trials  </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
        <h1> Trials: </h1>
        <div class="container bg-light">
                <table class="table table-striped mx-auto">
                        <thead>
                                <tr>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th> Creator</th>
                                        <th> Country</th>
                                        <th> City</th>
                                        <th></th>
                                        
                                </tr>
                        </thead>
                        <tbody>
                                {% for t in object_list %}
                                <form method='POST'>
                                        {% csrf_token %}
                                        <tr>
                                        <td>{{t.title}}</td>
					                    <td>{{t.description}}</td>
                                        <td>{{t.creator}}</td>
                                        <td>{{t.country}}</td>
                                        <td>{{t.city}}</td>
					                    <td><input type="submit" value="Delete Trial" class="btn btn-danger " formaction="{% url 'deleteTrial' title=t.title %}"></a></td>
                                        <td><input type="submit" value="Edit Trial" class="btn btn-success " formaction="{%url 'editTrial' title=t.title %}"></a></td>

                                </tr>
                                </form>
                                {% endfor %}
                        </tbody>

		</div>
</body>
</html>

trialapp/templates/trialapp/load_data.html
<h1>


    this data is generated from ajax call

</h1>

trialapp/templates/trialapp/operator_form.html
<!DOCTYPE html>
<html>
<head>
        <title> Update </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
        <div class="container bg-light">
                <form action="" method="POST">
                        <fieldset>
                                <legend> <h1 class='txt-info'>Update:</h1> </legend>
                                {% csrf_token %}
				                {{form.as_p}}
				                <input type="submit" value="Update" class="btn btn-primary float-right">
                        </fieldset>
                </form>
        </div>

</body>
</html>